- name: Container Images Sync
      uses: x-actions/python3-cisctl@v1
      env:
        GIT_ORG: "little-77"
        GIT_REPO: "fuzzbench-images"
        GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SRC_IMAGE_LIST_URL: "https://raw.githubusercontent.com/little-77/fuzzbench-images/main/dispatcher"
        DEST_REPO: "docker.io/gcmirrors"
        SRC_TRANSPORT: "docker"
        DEST_TRANSPORT: "docker"
        DEST_TRANSPORT_USER: "little77"
        DEST_TRANSPORT_PASSWORD: "950310CCyy"
        LOG_LEVEL: "DEBUG"
